# test my api for crm to huse

import requests
# from crm_to_db import crm_object
url = "http://localhost:5000/crm_to_huse"

headers = {
    "huse-api-key": "ghfdsnfviuhdfmnkdfiojdsdsmndskhdfknsdi"
}

crm_object = {'message': 'Lead created in CRM successfully', 'data': {'id': '68b00384acc17908c', 'name': 'Isabella Marie Thompson', 'deleted': False, 'firstName': 'Isabella', 'lastName': 'Marie Thompson', 'status': 'New', 'emailAddress': 'bella.thompson@innoventures.com', 'phoneNumber': '+14167894567', 'doNotCall': False, 'createdAt': '2025-08-28 07:21:40', 'modifiedAt': '2025-08-28 07:21:40', 'targetListIsOptedOut': False, 'cPreferredName': 'Bella', 'cApplicationDate': '2025-08-28', 'cGender': 'Male', 'cMembershipCategory': 'The Rufescent Business', 'cNationality': 'Canada', 'cDateOfBirth': '1990-07-22', 'cMaritalStatus': 'Single', 'cIdType': 'Emirates ID', 'cIdNumber': 'SSN-987-65-4321', 'cFullName': 'Isabella Marie Thompson', 'cJobTitle': 'Chief Technology Officer', 'cCompany': 'TechCorp Innovations', 'cEmailAddress': 'bella.thompson@innoventures.com', 'cPaMobileNumber': '+1-416-789-4567', 'cPaymentsMembershipCategory': 'The Rufescent Business', 'cMembershipAccountSettlementMethod': 'Time of consumption', 'cApplicantsName': 'Isabella Marie Thompson', 'cSignature': False, 'cLeadStatus': 'Hot', 'cWhichAspectsAreMostValuableToYou': [], 'cIWishToSettleMyMembershipAccountBy': [], 'cApprovalStatus': 'pending', 'cSpouseInformation': False, 'cIsPaInformation': False, 'cCPaymentMethod': 'G-Pay, Apple Pay, Card', 'cIsformsubmitted': False, 'emailAddressIsOptedOut': False, 'emailAddressIsInvalid': False, 'phoneNumberIsOptedOut': False, 'phoneNumberIsInvalid': False, 'streamUpdatedAt': '2025-08-28 07:21:40', 'emailAddressData': [{'emailAddress': 'bella.thompson@innoventures.com', 'lower': 'bella.thompson@innoventures.com', 'primary': True, 'optOut': False, 'invalid': False}], 'phoneNumberData': [{'phoneNumber': '+14167894567', 'type': 'Mobile', 'primary': True, 'optOut': False, 'invalid': False}], 'createdById': '684882bb7d1285cb4', 'createdByName': 'Admin', 'modifiedByName': None, 'assignedUserName': None, 'teamsIds': [], 'teamsNames': {}, 'campaignName': None, 'createdAccountName': None, 'createdContactName': None, 'createdOpportunityName': None, 'isFollowed': False, 'followersIds': [], 'followersNames': {}, 'profile_image': None, 'document_attachments': None, 'signature': None}, 'lead_form_url': 'https://dev-rufescent-experience.rufescent.com?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZWFkX2lkIjoiNjhiMDAzODRhY2MxNzkwOGMifQ.cCJAijJT76TDknfDZwdsHDaZKWHcobiNDpuku6ZPyLQ', 'aml_result_url': 'https://aml-pt2u.vercel.app/result?crm_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZWFkX2lkIjoiNjhiMDAzODRhY2MxNzkwOGMifQ.cCJAijJT76TDknfDZwdsHDaZKWHcobiNDpuku6ZPyLQ', 'failure': False}
response = requests.post(url, headers=headers, json=crm_object)
print(response.json())